server:
  port: 8088
#logback配置文件的地址
logging:
  config: classpath:logback-spring.xml

spring:
  #应用名
#  application:
#    name: web-admin
  #日志环境
  profiles:
    active: dev # dev|test|prd
  #数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.106.198.29:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://47.106.198.29:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: MysqL@951QwdC
    #hikari配置
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #页面
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  type-aliases-package: com.lwl.project.admin.pojo
  mapper-locations: classpath:mapper/*.xml
